# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neutron detector efficiency calculator
email: alvaro@esss.se
description: > # this means to ignore newlines until "baseurl:"
  Standalone tool to calculate the efficiency of a neutron detector
baseurl: "dg_efficiencyCalculator/" # the subpath of your site, e.g. /blog
url: "https://detectorefficiencycalculator.github.io/" # the base hostname & protocol for your site

software_name: Detector efficiency calculator
# Social media profiles - feel free to add more here
#twitter_username: SBootstrap
github_username:  alvcarmona
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/%C3%A1lvaro-carmona-bas%C3%A1%C3%B1ez-08bb56a7/

# Address information
address_street: European Spallation Source ERIC
address_city: Lund
address_state: Skåne, Sweden
address_zip: 22100

# Build settings
markdown: kramdown
